import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "zh" | "en" | "vi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Header
    "nav.services": "服務項目",
    "nav.quote": "報價試算",
    "nav.about": "關於我們",
    "nav.gallery": "作品展示",
    "nav.faq": "常見問題",
    "nav.booking": "立即預約",

    // Hero
    "hero.badge": "全方位美學沙龍",
    "hero.headline1": "讓妳的美，",
    "hero.headline2": "成為日常的儀式感",
    "hero.brand": "Trinhnai",
    "hero.services": "美甲・美睫・紋繡・熱蠟除毛",
    "hero.cta.booking": "立即預約",
    "hero.cta.line": "加入 LINE 諮詢",
    "hero.scroll": "探索更多",

    // Services
    "services.title": "我們的服務",
    "services.subtitle": "專業技術 × 安心體驗 × 一站式美學呵護",
    "services.nail.title": "美甲服務",
    "services.nail.subtitle": "Nail Art",
    "services.nail.desc": "光療、延甲、保養等客製化設計",
    "services.nail.cta": "查看美甲方案",
    "services.lash.title": "美睫設計",
    "services.lash.subtitle": "Eyelash Extension",
    "services.lash.desc": "經典 / 3D / 泰式層次設計",
    "services.lash.cta": "查看美睫方案",
    "services.tattoo.title": "半永久紋繡",
    "services.tattoo.subtitle": "Semi-Permanent Makeup",
    "services.tattoo.desc": "霧眉、霧唇、眼線，專業定妝技術",
    "services.tattoo.cta": "了解紋繡項目",
    "services.waxing.title": "熱蠟除毛",
    "services.waxing.subtitle": "Hot Wax Hair Removal",
    "services.waxing.desc": "全身熱蠟除毛與私密處護理",
    "services.waxing.cta": "查看除毛服務",

    // Brand
    "brand.title": "關於 Trinhnai",
    "brand.subtitle": "專業・安心・細緻・優雅",
    "brand.content1": "Trinhnai 相信，美麗是一種生活態度。從手部到眼神，我們為妳打造細節中的自信。",
    "brand.content2": "使用日本進口凝膠與醫療級消毒流程，確保每一次服務都安全無慮。",
    "brand.content3": "全館技師均具專業證照與多年以上實務經驗，讓妳在安心中綻放光彩。",
    "brand.feature1.title": "專業證照技師",
    "brand.feature1.desc": "經驗豐富的專業美容師",
    "brand.feature2.title": "醫療級消毒",
    "brand.feature2.desc": "嚴格衛生標準保障安全",
    "brand.feature3.title": "日本進口材料",
    "brand.feature3.desc": "高品質產品確保效果",
    "brand.feature4.title": "細緻服務",
    "brand.feature4.desc": "用心呵護每位顧客",

    // Gallery
    "gallery.title": "作品展示",
    "gallery.subtitle": "真實客照・自然光感",

    // Promotions
    "promo.title": "限時優惠",
    "promo.subtitle": "把握機會，讓美麗更超值",
    "promo.birthday.title": "壽星 85 折",
    "promo.birthday.desc": "當月壽星預約享全館 85 折優惠",
    "promo.review.title": "五星好評 95 折",
    "promo.review.desc": "留下五星評論即可享 95 折",
    "promo.combo.title": "足部光療 + 深層保養 9 折",
    "promo.combo.desc": "限時聯合保養方案",
    "promo.cta": "立即預約享優惠",

    // FAQ
    "faq.title": "常見問題",
    "faq.subtitle": "解答您的疑慮",
    "faq.q1": "孕婦可以做美睫或除毛嗎？",
    "faq.a1": "可於安全孕期中進行，使用低刺激材料並依個人狀況調整。",
    "faq.q2": "延甲會傷害真甲嗎？",
    "faq.a2": "我們採用高品質凝膠與正確卸除方式，不會傷害指甲。",
    "faq.q3": "服務後如何維護？",
    "faq.a3": "建議每 3–4 週回店保養，使用護手油與保濕精華維持效果。",
    "faq.trust.title": "安心保證",
    "faq.trust1.title": "醫療級消毒",
    "faq.trust1.desc": "所有器具皆經高溫消毒處理",
    "faq.trust2.title": "天然材料",
    "faq.trust2.desc": "使用低敏、無毒的優質產品",
    "faq.trust3.title": "專業服務",
    "faq.trust3.desc": "技師持續進修確保技術領先",

    // Booking
    "booking.title": "預約服務",
    "booking.subtitle": "只要 3 小時，給妳不後悔的美麗",
    "booking.name": "姓名",
    "booking.phone": "電話",
    "booking.line": "LINE ID",
    "booking.service": "服務項目",
    "booking.service.nail": "美甲",
    "booking.service.lash": "美睫",
    "booking.service.tattoo": "紋繡",
    "booking.service.waxing": "除毛",
    "booking.date": "預約日期",
    "booking.time": "預約時段",
    "booking.note": "備註",
    "booking.privacy": "我同意隱私條款",
    "booking.submit": "送出預約",
    "booking.success": "預約成功！我們將盡快與您聯繫 💖",
    "booking.close": "關閉",

    // Footer
    "footer.contact": "聯絡我們",
    "footer.hours": "營業時間",
    "footer.hours.value": "09:00–24:00（無休）",
    "footer.locations": "門市地址",
    "footer.location1": "中壢元化店（前站）",
    "footer.location2": "中壢忠福店（黃昏市場對面）",
    "footer.follow": "追蹤我們",
    "footer.copyright": "© 2026 Trinhnai All Rights Reserved.",

    // Sticky CTA
    "sticky.line": "LINE 諮詢",
    "sticky.booking": "立即預約",

    // Quote Page
    "quote.badge": "專屬報價",
    "quote.title": "試算你的專屬美麗報價",
    "quote.subtitle": "選擇服務，即時計算價格，輕鬆預約",
    "quote.step1": "第一步",
    "quote.step1.title": "選擇服務類別",
    "quote.step2": "第二步",
    "quote.step2.title": "選擇細項服務",
    "quote.step3": "第三步",
    "quote.step3.addons": "加購項目",
    "quote.step4": "第四步",
    "quote.step4.discount": "選擇優惠方案",
    "quote.result.title": "報價結果",
    "quote.result.subtitle": "即時計算您的專屬價格",
    "quote.result.subtotal": "小計",
    "quote.result.discount": "折扣",
    "quote.result.total": "優惠後金額",
    "quote.result.saved": "已省下",
    "quote.result.send": "發送報價",
    "quote.result.line": "LINE 諮詢",
    
    // Quote Categories
    "quote.cat.nail": "美甲服務",
    "quote.cat.nail.sub": "光療、延甲、設計",
    "quote.cat.lash": "美睫設計",
    "quote.cat.lash.sub": "經典、3D、泰式",
    "quote.cat.waxing": "熱蠟除毛",
    "quote.cat.waxing.sub": "全身部位除毛",
    "quote.cat.tattoo": "半永久紋繡",
    "quote.cat.tattoo.sub": "眉、唇、眼線",
    
    // Nail Services
    "quote.nail.handPlain": "手部素色光療",
    "quote.nail.handPlainCare": "手部素色 + 保養 + 卸",
    "quote.nail.footPlain": "足部素色光療",
    "quote.nail.footPlainCare": "足部素色 + 保養 + 卸",
    "quote.nail.handDesign": "手部設計款",
    "quote.nail.footDesign": "足部設計款",
    "quote.nail.extension": "凝膠延甲",
    "quote.nail.remove": "卸甲",
    "quote.nail.repair": "補甲（單指）",
    
    // Lash Services
    "quote.lash.classic": "經典款美睫",
    "quote.lash.3d": "3D 層次款",
    "quote.lash.3dDense": "3D 層次微濃",
    "quote.lash.thai": "泰式設計款",
    "quote.lash.thaiDense": "泰式設計微濃",
    "quote.lash.remove": "美睫卸除",
    
    // Waxing Services
    "quote.wax.underarm": "腋下除毛",
    "quote.wax.armHalf": "手臂半除毛",
    "quote.wax.armFull": "手臂全除毛",
    "quote.wax.legHalf": "腿部半除毛",
    "quote.wax.legFull": "腿部全除毛",
    "quote.wax.bikini": "比基尼線",
    "quote.wax.brazilian": "巴西式全除",
    "quote.wax.face": "臉部除毛",
    "quote.wax.back": "背部除毛",
    
    // Tattoo Services
    "quote.tattoo.browMist": "霧眉",
    "quote.tattoo.browStroke": "線條眉",
    "quote.tattoo.browCombo": "霧眉 + 線條",
    "quote.tattoo.lip": "霧唇",
    "quote.tattoo.eyeliner": "美瞳線",
    "quote.tattoo.hairline": "髮際線",
    
    // Add-ons
    "quote.addon.deepCare": "深層保養",
    "quote.addon.extendLash": "美睫加長",
    "quote.addon.handSpa": "手部 SPA",
    "quote.addon.footSpa": "足部 SPA",
    
    // Discounts
    "quote.discount.birthday": "壽星 85 折",
    "quote.discount.birthday.desc": "當月壽星專享優惠",
    "quote.discount.review": "五星好評 95 折",
    "quote.discount.review.desc": "留下五星評論即享折扣",
    "quote.discount.combo": "足部光療套餐 9 折",
    "quote.discount.combo.desc": "足部光療 + 深層保養",
    
    // Send Form
    "quote.send.title": "發送報價明細",
    "quote.send.quoteTitle": "報價明細",
    "quote.send.services": "服務項目",
    "quote.send.addons": "加購項目",
    "quote.send.discount": "優惠方案",
    "quote.send.preview": "報價預覽",
    "quote.send.name": "您的姓名",
    "quote.send.namePlaceholder": "請輸入姓名",
    "quote.send.contact": "聯絡方式",
    "quote.send.contactPlaceholder": "LINE ID 或電話",
    "quote.send.method": "發送方式",
    "quote.send.booking": "預約",
    "quote.send.copy": "複製報價",
    "quote.send.submit": "發送",
    "quote.send.copied": "已複製！",
    "quote.send.copiedDesc": "報價明細已複製到剪貼簿",
    "quote.send.success": "報價已發送！",
    "quote.send.successDesc": "我們將盡快與您聯繫 💖",
    
    // Lead Capture
    "lead.title": "讓我們為妳設計專屬美麗體驗 💖",
    "lead.subtitle": "留下資料，Trinhnai 將寄送最新優惠與美麗靈感給妳。",
    "lead.name": "妳的稱呼",
    "lead.namePlaceholder": "例：王小姐、小美",
    "lead.email": "Email 信箱",
    "lead.emailPlaceholder": "example@email.com",
    "lead.service": "想了解的服務",
    "lead.servicePlaceholder": "請選擇服務",
    "lead.timeframe": "想預約的時間",
    "lead.timeframePlaceholder": "請選擇時間",
    "lead.timeframe.thisWeek": "這週",
    "lead.timeframe.nextWeek": "下週",
    "lead.timeframe.justLooking": "先了解看看",
    "lead.consent": "同意接收優惠通知",
    "lead.submit": "送出資料",
    "lead.submitting": "處理中...",
    "lead.success.title": "感謝妳 💫",
    "lead.success.desc": "我們將寄送最新優惠與美麗靈感給妳！",
    "lead.error.title": "發生錯誤",
    "lead.error.desc": "請稍後再試或聯繫我們",
  },
  en: {
    // Header
    "nav.services": "Services",
    "nav.quote": "Quote",
    "nav.about": "About Us",
    "nav.gallery": "Gallery",
    "nav.faq": "FAQ",
    "nav.booking": "Book Now",

    // Hero
    "hero.badge": "Full-Service Beauty Salon",
    "hero.headline1": "Let Your Beauty",
    "hero.headline2": "Become a Daily Ritual",
    "hero.brand": "Trinhnai",
    "hero.services": "Nails・Lashes・Tattoo・Waxing",
    "hero.cta.booking": "Book Now",
    "hero.cta.line": "Chat on LINE",
    "hero.scroll": "Explore More",

    // Services
    "services.title": "Our Services",
    "services.subtitle": "Professional Skills × Safe Experience × One-Stop Beauty Care",
    "services.nail.title": "Nail Services",
    "services.nail.subtitle": "Nail Art",
    "services.nail.desc": "Gel, extensions, care and custom designs",
    "services.nail.cta": "View Nail Services",
    "services.lash.title": "Eyelash Design",
    "services.lash.subtitle": "Eyelash Extension",
    "services.lash.desc": "Classic / 3D / Thai layered design",
    "services.lash.cta": "View Lash Services",
    "services.tattoo.title": "Semi-Permanent Makeup",
    "services.tattoo.subtitle": "Semi-Permanent Makeup",
    "services.tattoo.desc": "Microblading, lip blush, eyeliner",
    "services.tattoo.cta": "View Tattoo Services",
    "services.waxing.title": "Hot Wax Hair Removal",
    "services.waxing.subtitle": "Hot Wax Hair Removal",
    "services.waxing.desc": "Full body waxing and intimate care",
    "services.waxing.cta": "View Waxing Services",

    // Brand
    "brand.title": "About Trinhnai",
    "brand.subtitle": "Professional・Safe・Delicate・Elegant",
    "brand.content1": "Trinhnai believes that beauty is a lifestyle. From hands to eyes, we build your confidence in every detail.",
    "brand.content2": "Using Japanese imported gel and medical-grade sterilization, ensuring every service is safe.",
    "brand.content3": "All technicians are certified with years of experience, letting you shine with peace of mind.",
    "brand.feature1.title": "Certified Technicians",
    "brand.feature1.desc": "Experienced beauty professionals",
    "brand.feature2.title": "Medical-Grade Sterilization",
    "brand.feature2.desc": "Strict hygiene standards for safety",
    "brand.feature3.title": "Japanese Imported Materials",
    "brand.feature3.desc": "High-quality products for best results",
    "brand.feature4.title": "Attentive Service",
    "brand.feature4.desc": "Caring for every customer",

    // Gallery
    "gallery.title": "Our Work",
    "gallery.subtitle": "Real Photos・Natural Light",

    // Promotions
    "promo.title": "Special Offers",
    "promo.subtitle": "Seize the opportunity for more value",
    "promo.birthday.title": "Birthday 15% Off",
    "promo.birthday.desc": "Birthday month guests enjoy 15% off all services",
    "promo.review.title": "5-Star Review 5% Off",
    "promo.review.desc": "Leave a 5-star review for 5% off",
    "promo.combo.title": "Foot Gel + Deep Care 10% Off",
    "promo.combo.desc": "Limited time combo package",
    "promo.cta": "Book Now for Discount",

    // FAQ
    "faq.title": "FAQ",
    "faq.subtitle": "Answering Your Questions",
    "faq.q1": "Can pregnant women get lash extensions or waxing?",
    "faq.a1": "Available during safe pregnancy periods, using low-irritation materials adjusted to individual conditions.",
    "faq.q2": "Will nail extensions damage natural nails?",
    "faq.a2": "We use high-quality gel and proper removal techniques that won't damage your nails.",
    "faq.q3": "How to maintain after service?",
    "faq.a3": "We recommend returning every 3-4 weeks for maintenance, using hand oil and moisturizing serum.",
    "faq.trust.title": "Quality Assurance",
    "faq.trust1.title": "Medical-Grade Sterilization",
    "faq.trust1.desc": "All tools are high-temperature sterilized",
    "faq.trust2.title": "Natural Materials",
    "faq.trust2.desc": "Using hypoallergenic, non-toxic products",
    "faq.trust3.title": "Professional Service",
    "faq.trust3.desc": "Technicians continuously upgrade their skills",

    // Booking
    "booking.title": "Book a Service",
    "booking.subtitle": "Just 3 hours for beauty you won't regret",
    "booking.name": "Name",
    "booking.phone": "Phone",
    "booking.line": "LINE ID",
    "booking.service": "Service",
    "booking.service.nail": "Nails",
    "booking.service.lash": "Lashes",
    "booking.service.tattoo": "Tattoo",
    "booking.service.waxing": "Waxing",
    "booking.date": "Date",
    "booking.time": "Time",
    "booking.note": "Notes",
    "booking.privacy": "I agree to the privacy policy",
    "booking.submit": "Submit Booking",
    "booking.success": "Booking successful! We'll contact you soon 💖",
    "booking.close": "Close",

    // Footer
    "footer.contact": "Contact Us",
    "footer.hours": "Business Hours",
    "footer.hours.value": "09:00–24:00 (Open Daily)",
    "footer.locations": "Locations",
    "footer.location1": "Zhongli Yuanhua Store (Front Station)",
    "footer.location2": "Zhongli Zhongfu Store (Opposite Evening Market)",
    "footer.follow": "Follow Us",
    "footer.copyright": "© 2026 Trinhnai All Rights Reserved.",

    // Sticky CTA
    "sticky.line": "LINE Chat",
    "sticky.booking": "Book Now",

    // Quote Page
    "quote.badge": "Custom Quote",
    "quote.title": "Calculate Your Beauty Quote",
    "quote.subtitle": "Select services, get instant pricing, easy booking",
    "quote.step1": "Step 1",
    "quote.step1.title": "Choose Category",
    "quote.step2": "Step 2",
    "quote.step2.title": "Select Services",
    "quote.step3": "Step 3",
    "quote.step3.addons": "Add-ons",
    "quote.step4": "Step 4",
    "quote.step4.discount": "Choose Discount",
    "quote.result.title": "Your Quote",
    "quote.result.subtitle": "Instant calculation of your price",
    "quote.result.subtotal": "Subtotal",
    "quote.result.discount": "Discount",
    "quote.result.total": "Total",
    "quote.result.saved": "You saved",
    "quote.result.send": "Send Quote",
    "quote.result.line": "LINE Chat",
    
    // Quote Categories
    "quote.cat.nail": "Nail Services",
    "quote.cat.nail.sub": "Gel, Extensions, Design",
    "quote.cat.lash": "Lash Design",
    "quote.cat.lash.sub": "Classic, 3D, Thai",
    "quote.cat.waxing": "Hot Wax",
    "quote.cat.waxing.sub": "Full Body Waxing",
    "quote.cat.tattoo": "Semi-Permanent",
    "quote.cat.tattoo.sub": "Brows, Lips, Eyeliner",
    
    // Nail Services
    "quote.nail.handPlain": "Hand Plain Gel",
    "quote.nail.handPlainCare": "Hand Plain + Care + Removal",
    "quote.nail.footPlain": "Foot Plain Gel",
    "quote.nail.footPlainCare": "Foot Plain + Care + Removal",
    "quote.nail.handDesign": "Hand Design",
    "quote.nail.footDesign": "Foot Design",
    "quote.nail.extension": "Gel Extensions",
    "quote.nail.remove": "Removal",
    "quote.nail.repair": "Repair (Single)",
    
    // Lash Services
    "quote.lash.classic": "Classic Lashes",
    "quote.lash.3d": "3D Volume",
    "quote.lash.3dDense": "3D Volume Dense",
    "quote.lash.thai": "Thai Design",
    "quote.lash.thaiDense": "Thai Design Dense",
    "quote.lash.remove": "Lash Removal",
    
    // Waxing Services
    "quote.wax.underarm": "Underarm",
    "quote.wax.armHalf": "Half Arm",
    "quote.wax.armFull": "Full Arm",
    "quote.wax.legHalf": "Half Leg",
    "quote.wax.legFull": "Full Leg",
    "quote.wax.bikini": "Bikini Line",
    "quote.wax.brazilian": "Brazilian",
    "quote.wax.face": "Face",
    "quote.wax.back": "Back",
    
    // Tattoo Services
    "quote.tattoo.browMist": "Powder Brows",
    "quote.tattoo.browStroke": "Microblading",
    "quote.tattoo.browCombo": "Combo Brows",
    "quote.tattoo.lip": "Lip Blush",
    "quote.tattoo.eyeliner": "Eyeliner",
    "quote.tattoo.hairline": "Hairline",
    
    // Add-ons
    "quote.addon.deepCare": "Deep Care",
    "quote.addon.extendLash": "Lash Extension",
    "quote.addon.handSpa": "Hand SPA",
    "quote.addon.footSpa": "Foot SPA",
    
    // Discounts
    "quote.discount.birthday": "Birthday 15% Off",
    "quote.discount.birthday.desc": "Birthday month exclusive",
    "quote.discount.review": "5-Star Review 5% Off",
    "quote.discount.review.desc": "Leave a 5-star review",
    "quote.discount.combo": "Foot Combo 10% Off",
    "quote.discount.combo.desc": "Foot gel + deep care",
    
    // Send Form
    "quote.send.title": "Send Quote Details",
    "quote.send.quoteTitle": "Quote Details",
    "quote.send.services": "Services",
    "quote.send.addons": "Add-ons",
    "quote.send.discount": "Discount",
    "quote.send.preview": "Quote Preview",
    "quote.send.name": "Your Name",
    "quote.send.namePlaceholder": "Enter your name",
    "quote.send.contact": "Contact",
    "quote.send.contactPlaceholder": "LINE ID or Phone",
    "quote.send.method": "Send Method",
    "quote.send.booking": "Book",
    "quote.send.copy": "Copy Quote",
    "quote.send.submit": "Send",
    "quote.send.copied": "Copied!",
    "quote.send.copiedDesc": "Quote copied to clipboard",
    "quote.send.success": "Quote Sent!",
    "quote.send.successDesc": "We'll contact you soon 💖",
    
    // Lead Capture
    "lead.title": "Let Us Design Your Exclusive Beauty Experience 💖",
    "lead.subtitle": "Leave your info and Trinhnai will send you the latest offers and beauty inspiration.",
    "lead.name": "Your Name",
    "lead.namePlaceholder": "e.g. Ms. Wang, Mei",
    "lead.email": "Email",
    "lead.emailPlaceholder": "example@email.com",
    "lead.service": "Service Interest",
    "lead.servicePlaceholder": "Select a service",
    "lead.timeframe": "Preferred Booking Time",
    "lead.timeframePlaceholder": "Select timeframe",
    "lead.timeframe.thisWeek": "This Week",
    "lead.timeframe.nextWeek": "Next Week",
    "lead.timeframe.justLooking": "Just Looking",
    "lead.consent": "Agree to receive promotional notifications",
    "lead.submit": "Submit",
    "lead.submitting": "Processing...",
    "lead.success.title": "Thank You 💫",
    "lead.success.desc": "We'll send you the latest offers and beauty inspiration!",
    "lead.error.title": "Error Occurred",
    "lead.error.desc": "Please try again later or contact us",
  },
  vi: {
    // Header
    "nav.services": "Dịch vụ",
    "nav.quote": "Báo Giá",
    "nav.about": "Về chúng tôi",
    "nav.gallery": "Bộ sưu tập",
    "nav.faq": "Câu hỏi thường gặp",
    "nav.booking": "Đặt lịch ngay",

    // Hero
    "hero.badge": "Salon Thẩm Mỹ Toàn Diện",
    "hero.headline1": "Để Vẻ Đẹp Của Bạn",
    "hero.headline2": "Trở Thành Nghi Thức Hàng Ngày",
    "hero.brand": "Trinhnai",
    "hero.services": "Móng・Mi・Xăm・Wax",
    "hero.cta.booking": "Đặt Lịch Ngay",
    "hero.cta.line": "Tư Vấn LINE",
    "hero.scroll": "Khám Phá Thêm",

    // Services
    "services.title": "Dịch Vụ Của Chúng Tôi",
    "services.subtitle": "Kỹ Thuật Chuyên Nghiệp × Trải Nghiệm An Toàn × Chăm Sóc Sắc Đẹp Toàn Diện",
    "services.nail.title": "Dịch Vụ Móng",
    "services.nail.subtitle": "Nail Art",
    "services.nail.desc": "Gel, đắp móng, chăm sóc và thiết kế tùy chỉnh",
    "services.nail.cta": "Xem Dịch Vụ Móng",
    "services.lash.title": "Thiết Kế Mi",
    "services.lash.subtitle": "Eyelash Extension",
    "services.lash.desc": "Cổ điển / 3D / Thiết kế lớp kiểu Thái",
    "services.lash.cta": "Xem Dịch Vụ Mi",
    "services.tattoo.title": "Xăm Bán Vĩnh Viễn",
    "services.tattoo.subtitle": "Semi-Permanent Makeup",
    "services.tattoo.desc": "Phun mày, phun môi, kẻ mắt",
    "services.tattoo.cta": "Xem Dịch Vụ Xăm",
    "services.waxing.title": "Wax Lông Nóng",
    "services.waxing.subtitle": "Hot Wax Hair Removal",
    "services.waxing.desc": "Wax toàn thân và chăm sóc vùng kín",
    "services.waxing.cta": "Xem Dịch Vụ Wax",

    // Brand
    "brand.title": "Về Trinhnai",
    "brand.subtitle": "Chuyên Nghiệp・An Toàn・Tinh Tế・Sang Trọng",
    "brand.content1": "Trinhnai tin rằng vẻ đẹp là một lối sống. Từ bàn tay đến ánh mắt, chúng tôi xây dựng sự tự tin của bạn trong từng chi tiết.",
    "brand.content2": "Sử dụng gel nhập khẩu Nhật Bản và quy trình khử trùng cấp y tế, đảm bảo mọi dịch vụ đều an toàn.",
    "brand.content3": "Tất cả kỹ thuật viên đều có chứng chỉ với nhiều năm kinh nghiệm, giúp bạn tỏa sáng với sự an tâm.",
    "brand.feature1.title": "Kỹ Thuật Viên Có Chứng Chỉ",
    "brand.feature1.desc": "Chuyên gia làm đẹp giàu kinh nghiệm",
    "brand.feature2.title": "Khử Trùng Cấp Y Tế",
    "brand.feature2.desc": "Tiêu chuẩn vệ sinh nghiêm ngặt để an toàn",
    "brand.feature3.title": "Nguyên Liệu Nhập Khẩu Nhật Bản",
    "brand.feature3.desc": "Sản phẩm chất lượng cao cho kết quả tốt nhất",
    "brand.feature4.title": "Dịch Vụ Chu Đáo",
    "brand.feature4.desc": "Chăm sóc từng khách hàng",

    // Gallery
    "gallery.title": "Tác Phẩm",
    "gallery.subtitle": "Ảnh Thực・Ánh Sáng Tự Nhiên",

    // Promotions
    "promo.title": "Ưu Đãi Đặc Biệt",
    "promo.subtitle": "Nắm bắt cơ hội để có giá trị hơn",
    "promo.birthday.title": "Sinh Nhật Giảm 15%",
    "promo.birthday.desc": "Khách sinh nhật trong tháng được giảm 15% tất cả dịch vụ",
    "promo.review.title": "Đánh Giá 5 Sao Giảm 5%",
    "promo.review.desc": "Để lại đánh giá 5 sao để được giảm 5%",
    "promo.combo.title": "Gel Chân + Chăm Sóc Sâu Giảm 10%",
    "promo.combo.desc": "Gói combo thời gian có hạn",
    "promo.cta": "Đặt Ngay Để Được Giảm Giá",

    // FAQ
    "faq.title": "Câu Hỏi Thường Gặp",
    "faq.subtitle": "Giải Đáp Thắc Mắc Của Bạn",
    "faq.q1": "Phụ nữ mang thai có thể làm mi hoặc wax không?",
    "faq.a1": "Có thể thực hiện trong thời kỳ mang thai an toàn, sử dụng vật liệu ít kích ứng và điều chỉnh theo tình trạng cá nhân.",
    "faq.q2": "Đắp móng có làm hỏng móng tự nhiên không?",
    "faq.a2": "Chúng tôi sử dụng gel chất lượng cao và kỹ thuật tháo đúng cách, không làm hỏng móng của bạn.",
    "faq.q3": "Làm thế nào để bảo dưỡng sau dịch vụ?",
    "faq.a3": "Chúng tôi khuyên bạn nên quay lại mỗi 3-4 tuần để bảo dưỡng, sử dụng dầu dưỡng tay và serum dưỡng ẩm.",
    "faq.trust.title": "Đảm Bảo Chất Lượng",
    "faq.trust1.title": "Khử Trùng Cấp Y Tế",
    "faq.trust1.desc": "Tất cả dụng cụ được khử trùng nhiệt độ cao",
    "faq.trust2.title": "Nguyên Liệu Tự Nhiên",
    "faq.trust2.desc": "Sử dụng sản phẩm không gây dị ứng, không độc hại",
    "faq.trust3.title": "Dịch Vụ Chuyên Nghiệp",
    "faq.trust3.desc": "Kỹ thuật viên liên tục nâng cao kỹ năng",

    // Booking
    "booking.title": "Đặt Lịch Dịch Vụ",
    "booking.subtitle": "Chỉ 3 giờ cho vẻ đẹp bạn sẽ không hối hận",
    "booking.name": "Họ tên",
    "booking.phone": "Điện thoại",
    "booking.line": "LINE ID",
    "booking.service": "Dịch vụ",
    "booking.service.nail": "Móng",
    "booking.service.lash": "Mi",
    "booking.service.tattoo": "Xăm",
    "booking.service.waxing": "Wax",
    "booking.date": "Ngày",
    "booking.time": "Giờ",
    "booking.note": "Ghi chú",
    "booking.privacy": "Tôi đồng ý với chính sách bảo mật",
    "booking.submit": "Gửi Đặt Lịch",
    "booking.success": "Đặt lịch thành công! Chúng tôi sẽ liên hệ bạn sớm 💖",
    "booking.close": "Đóng",

    // Footer
    "footer.contact": "Liên Hệ",
    "footer.hours": "Giờ Làm Việc",
    "footer.hours.value": "09:00–24:00 (Mở cửa hàng ngày)",
    "footer.locations": "Địa Chỉ",
    "footer.location1": "Cửa hàng Zhongli Yuanhua (Ga trước)",
    "footer.location2": "Cửa hàng Zhongli Zhongfu (Đối diện chợ chiều)",
    "footer.follow": "Theo Dõi Chúng Tôi",
    "footer.copyright": "© 2026 Trinhnai All Rights Reserved.",

    // Sticky CTA
    "sticky.line": "LINE Tư Vấn",
    "sticky.booking": "Đặt Lịch Ngay",

    // Quote Page (Vietnamese)
    "quote.badge": "Báo Giá Riêng",
    "quote.title": "Tính Toán Báo Giá Làm Đẹp",
    "quote.subtitle": "Chọn dịch vụ, tính giá ngay, đặt lịch dễ dàng",
    "quote.step1": "Bước 1",
    "quote.step1.title": "Chọn Loại Dịch Vụ",
    "quote.step2": "Bước 2",
    "quote.step2.title": "Chọn Dịch Vụ Chi Tiết",
    "quote.step3": "Bước 3",
    "quote.step3.addons": "Dịch Vụ Thêm",
    "quote.step4": "Bước 4",
    "quote.step4.discount": "Chọn Ưu Đãi",
    "quote.result.title": "Báo Giá Của Bạn",
    "quote.result.subtitle": "Tính toán giá ngay lập tức",
    "quote.result.subtotal": "Tạm tính",
    "quote.result.discount": "Giảm giá",
    "quote.result.total": "Tổng cộng",
    "quote.result.saved": "Tiết kiệm",
    "quote.result.send": "Gửi Báo Giá",
    "quote.result.line": "LINE Tư Vấn",
    "quote.cat.nail": "Dịch Vụ Móng",
    "quote.cat.nail.sub": "Gel, Đắp, Thiết Kế",
    "quote.cat.lash": "Thiết Kế Mi",
    "quote.cat.lash.sub": "Cổ điển, 3D, Thái",
    "quote.cat.waxing": "Wax Nóng",
    "quote.cat.waxing.sub": "Wax Toàn Thân",
    "quote.cat.tattoo": "Xăm Bán Vĩnh Viễn",
    "quote.cat.tattoo.sub": "Mày, Môi, Mắt",
    "quote.nail.handPlain": "Gel Tay Đơn Sắc",
    "quote.nail.handPlainCare": "Gel Tay + Chăm Sóc + Tháo",
    "quote.nail.footPlain": "Gel Chân Đơn Sắc",
    "quote.nail.footPlainCare": "Gel Chân + Chăm Sóc + Tháo",
    "quote.nail.handDesign": "Thiết Kế Tay",
    "quote.nail.footDesign": "Thiết Kế Chân",
    "quote.nail.extension": "Đắp Gel",
    "quote.nail.remove": "Tháo Móng",
    "quote.nail.repair": "Sửa (1 ngón)",
    "quote.lash.classic": "Mi Cổ Điển",
    "quote.lash.3d": "3D Volume",
    "quote.lash.3dDense": "3D Volume Dày",
    "quote.lash.thai": "Kiểu Thái",
    "quote.lash.thaiDense": "Kiểu Thái Dày",
    "quote.lash.remove": "Tháo Mi",
    "quote.wax.underarm": "Nách",
    "quote.wax.armHalf": "Nửa Tay",
    "quote.wax.armFull": "Cả Tay",
    "quote.wax.legHalf": "Nửa Chân",
    "quote.wax.legFull": "Cả Chân",
    "quote.wax.bikini": "Bikini",
    "quote.wax.brazilian": "Brazilian",
    "quote.wax.face": "Mặt",
    "quote.wax.back": "Lưng",
    "quote.tattoo.browMist": "Phun Mày",
    "quote.tattoo.browStroke": "Điêu Khắc Mày",
    "quote.tattoo.browCombo": "Combo Mày",
    "quote.tattoo.lip": "Phun Môi",
    "quote.tattoo.eyeliner": "Kẻ Mắt",
    "quote.tattoo.hairline": "Đường Chân Tóc",
    "quote.addon.deepCare": "Chăm Sóc Sâu",
    "quote.addon.extendLash": "Nối Mi",
    "quote.addon.handSpa": "SPA Tay",
    "quote.addon.footSpa": "SPA Chân",
    "quote.discount.birthday": "Sinh Nhật Giảm 15%",
    "quote.discount.birthday.desc": "Ưu đãi tháng sinh nhật",
    "quote.discount.review": "5 Sao Giảm 5%",
    "quote.discount.review.desc": "Đánh giá 5 sao",
    "quote.discount.combo": "Combo Chân Giảm 10%",
    "quote.discount.combo.desc": "Gel chân + chăm sóc sâu",
    "quote.send.title": "Gửi Chi Tiết Báo Giá",
    "quote.send.quoteTitle": "Chi Tiết Báo Giá",
    "quote.send.services": "Dịch vụ",
    "quote.send.addons": "Thêm",
    "quote.send.discount": "Ưu đãi",
    "quote.send.preview": "Xem trước",
    "quote.send.name": "Tên của bạn",
    "quote.send.namePlaceholder": "Nhập tên",
    "quote.send.contact": "Liên hệ",
    "quote.send.contactPlaceholder": "LINE ID hoặc SĐT",
    "quote.send.method": "Phương thức gửi",
    "quote.send.booking": "Đặt",
    "quote.send.copy": "Sao chép",
    "quote.send.submit": "Gửi",
    "quote.send.copied": "Đã sao chép!",
    "quote.send.copiedDesc": "Đã sao chép báo giá",
    "quote.send.success": "Đã gửi!",
    "quote.send.successDesc": "Chúng tôi sẽ liên hệ bạn sớm 💖",
    
    // Lead Capture
    "lead.title": "Để Chúng Tôi Thiết Kế Trải Nghiệm Làm Đẹp Độc Quyền Cho Bạn 💖",
    "lead.subtitle": "Để lại thông tin và Trinhnai sẽ gửi ưu đãi mới nhất và cảm hứng làm đẹp cho bạn.",
    "lead.name": "Tên của bạn",
    "lead.namePlaceholder": "VD: Chị Wang, Mei",
    "lead.email": "Email",
    "lead.emailPlaceholder": "example@email.com",
    "lead.service": "Dịch vụ quan tâm",
    "lead.servicePlaceholder": "Chọn dịch vụ",
    "lead.timeframe": "Thời gian đặt lịch mong muốn",
    "lead.timeframePlaceholder": "Chọn thời gian",
    "lead.timeframe.thisWeek": "Tuần này",
    "lead.timeframe.nextWeek": "Tuần sau",
    "lead.timeframe.justLooking": "Chỉ tìm hiểu",
    "lead.consent": "Đồng ý nhận thông báo khuyến mãi",
    "lead.submit": "Gửi",
    "lead.submitting": "Đang xử lý...",
    "lead.success.title": "Cảm ơn bạn 💫",
    "lead.success.desc": "Chúng tôi sẽ gửi ưu đãi mới nhất và cảm hứng làm đẹp cho bạn!",
    "lead.error.title": "Đã xảy ra lỗi",
    "lead.error.desc": "Vui lòng thử lại sau hoặc liên hệ chúng tôi",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("zh");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
